### ISSUE TITLE
The fullscreen button is not reset when forcefully exiting fullscreen

### ISSUE THREAD

**Issue by meiersi** [achirkin/ghcjs-modeler#1]
The fullscreen button toggles between two states that should reflect what happens when clicking on it. A square for full-screen-mode and an inverted square for windowed-mode. I entered full-screen, but used chrome to exit it immediately without clicking the button. This event was not tracked and left the button in the wrong state (windowed-mode).

**Comment by meiersi** [comment]
(Cool project BTW. Why don't you point out which parts you'd like to have reviewed the most.)

**Comment by achirkin** [comment]
Thanks, i fixed the bug. In the process of thinking what to show for the review :)
